<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'wrench-2 (plumber set)' =>$set . '_f100',
	'washing-machine-1 (plumber set)' =>$set . '_f101',
	'soap-1 (plumber set)' =>$set . '_f102',
	'washing-machine (plumber set)' =>$set . '_f103',
	'valve-1 (plumber set)' =>$set . '_f104',
	'valve (plumber set)' =>$set . '_f105',
	'toolbox-1 (plumber set)' =>$set . '_f106',
	'wrench-1 (plumber set)' =>$set . '_f107',
	'toolbox (plumber set)' =>$set . '_f108',
	'toilet (plumber set)' =>$set . '_f109',
	'faucet (plumber set)' =>$set . '_f10a',
	'tap (plumber set)' =>$set . '_f10b',
	'wrench (plumber set)' =>$set . '_f10c',
	'soap (plumber set)' =>$set . '_f10d',
	'shower-4 (plumber set)' =>$set . '_f10e',
	'shower-3 (plumber set)' =>$set . '_f10f',
	'shower-2 (plumber set)' =>$set . '_f110',
	'shower-1 (plumber set)' =>$set . '_f111',
	'shower (plumber set)' =>$set . '_f112',
	'screwdriver-1 (plumber set)' =>$set . '_f113',
	'screwdriver (plumber set)' =>$set . '_f114',
	'clipboard (plumber set)' =>$set . '_f115',
	'plunger (plumber set)' =>$set . '_f116',
	'detergent-5 (plumber set)' =>$set . '_f117',
	'truck (plumber set)' =>$set . '_f118',
	'plumber-1 (plumber set)' =>$set . '_f119',
	'plumber (plumber set)' =>$set . '_f11a',
	'pipe-6 (plumber set)' =>$set . '_f11b',
	'pipe-5 (plumber set)' =>$set . '_f11c',
	'pipe-4 (plumber set)' =>$set . '_f11d',
	'pipe-3 (plumber set)' =>$set . '_f11e',
	'pipe-2 (plumber set)' =>$set . '_f11f',
	'pipe-1 (plumber set)' =>$set . '_f120',
	'pipe (plumber set)' =>$set . '_f121',
	'notebook (plumber set)' =>$set . '_f122',
	'cogwheel-1 (plumber set)' =>$set . '_f123',
	'detergent-4 (plumber set)' =>$set . '_f124',
	'leak-2 (plumber set)' =>$set . '_f125',
	'leak-1 (plumber set)' =>$set . '_f126',
	'leak (plumber set)' =>$set . '_f127',
	'house (plumber set)' =>$set . '_f128',
	'helmet (plumber set)' =>$set . '_f129',
	'gauge (plumber set)' =>$set . '_f12a',
	'detergent-3 (plumber set)' =>$set . '_f12b',
	'cogwheel (plumber set)' =>$set . '_f12c',
	'detergent-2 (plumber set)' =>$set . '_f12d',
	'detergent-1 (plumber set)' =>$set . '_f12e',
	'cleaning (plumber set)' =>$set . '_f12f',
	'detergent (plumber set)' =>$set . '_f130',
	'caution (plumber set)' =>$set . '_f131'
);